// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaWebCooperativa.Models;

#nullable disable

namespace SistemaWebCooperativa.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221124004642_Upd1")]
    partial class Upd1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaWebCooperativa.Models.Cooperado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("propriedadeid")
                        .HasColumnType("int");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("id");

                    b.HasIndex("propriedadeid");

                    b.ToTable("Cooperado");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Insumo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<float>("preco")
                        .HasColumnType("real");

                    b.Property<float>("quantidade")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Insumo");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Producao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("cooperadoid")
                        .HasColumnType("int");

                    b.Property<int>("produtoid")
                        .HasColumnType("int");

                    b.Property<float>("quantidade")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("cooperadoid");

                    b.HasIndex("produtoid");

                    b.ToTable("Producao");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<float>("preco")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("area")
                        .HasColumnType("real");

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("uf")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Propriedade");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Transacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("operacao")
                        .HasColumnType("int");

                    b.Property<int>("producaoid")
                        .HasColumnType("int");

                    b.Property<float>("quantidade")
                        .HasColumnType("real");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("producaoid");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Cooperado", b =>
                {
                    b.HasOne("SistemaWebCooperativa.Models.Propriedade", "propriedade")
                        .WithMany("cooperados")
                        .HasForeignKey("propriedadeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("propriedade");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Producao", b =>
                {
                    b.HasOne("SistemaWebCooperativa.Models.Cooperado", "cooperado")
                        .WithMany("producoes")
                        .HasForeignKey("cooperadoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWebCooperativa.Models.Produto", "produto")
                        .WithMany("producoes")
                        .HasForeignKey("produtoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cooperado");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Transacao", b =>
                {
                    b.HasOne("SistemaWebCooperativa.Models.Producao", "producao")
                        .WithMany("transacoes")
                        .HasForeignKey("producaoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producao");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Cooperado", b =>
                {
                    b.Navigation("producoes");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Producao", b =>
                {
                    b.Navigation("transacoes");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Produto", b =>
                {
                    b.Navigation("producoes");
                });

            modelBuilder.Entity("SistemaWebCooperativa.Models.Propriedade", b =>
                {
                    b.Navigation("cooperados");
                });
#pragma warning restore 612, 618
        }
    }
}
